[WIP] INFINITY ROAD
mendesbarreto/BSToysGame pull request #1
Opened 2017-05-30 14:04 UTC by gustavox13

2017-05-30 17:18 UTC, mendesbarreto requested changes

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +public class SpawnStreetScript : MonoBehaviour {
Se a classe não for para ser herdada deveria ter o sinal de sealed

public sealed class

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +	void Start(){
Inserir o access control das funções da classe.. public, internal, protected ou private

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +	void Update () {
Inserir o access control das funções da classe.. public, internal, protected ou private

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +	void ChangeStreet(){
Inserir o access control das funções da classe.. public, internal, protected ou private

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +	void SpawnStreet() {
Inserir o access control das funções da classe.. public, internal, protected ou private

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +	public GameObject street1;
O que é street 1, 2 e 3? Mudar nome para middleStreet, leftStreet or rightStreet. Não é bom dar nome de variaveis com numeros, elas tem que refletir exatamente sua responsabilidade

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/StreetScript.cs
> +public class StreetScript : MonoBehaviour {
Se a classe não for para ser herdada deveria ter o sinal de sealed

public sealed class

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/StreetScript.cs
> +	public static bool isDestroyed = false;
Problema na indentação do código

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/StreetScript.cs
> +	void Update () {
Inserir o access control das funções da classe.. public, internal, protected ou private

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/StreetScript.cs
> +    void Destroy()
Inserir o access control das funções da classe.. public, internal, protected ou private

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/StreetScript.cs
> +        if (gameObject.transform.position.z == -100)
O que é -100 ?? 
Inserir em uma constante na declaração da classe...

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/StreetScript.cs
> +public class StreetScript : MonoBehaviour {
StreetScript não é um nome bom para uma classe... A classe define o comportamento de um objeto e sua estrutura, o nome deve refletir o que ela faz.. Pois script é muito generico

2017-05-30 17:18 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +public class SpawnStreetScript : MonoBehaviour {
Remover Script do nome da classe. 

Uma sugestão é colocar o nome da classe de StreetSpawner ou StreetBuilder, que seria um objeto que instancia a rua para vc. 

Seguindo o Design Pattern Builder ou Factory o nome da classe deve conter Factory ou Builder no nome.... por exemplo:

StreetFactory ou StreetBuilder . 

Assim fica bem claro o que a classe faz

2017-05-30 17:28 UTC, gustavox13 commented on Assets/Scripts/SpawnStreetScript.cs
> +public class SpawnStreetScript : MonoBehaviour {
Qual a diferença de colocar builder ou factory? tanto faz usar qualquer um dos dois?

2017-05-30 17:31 UTC, gustavox13 commented on Assets/Scripts/SpawnStreetScript.cs
> +	public GameObject street1;
Estes gameObjects são os tipos de patterns da rua, seria CityStreet, Coutry, e Highway

2017-05-30 17:36 UTC, gustavox13 commented on Assets/Scripts/StreetScript.cs
> +public class StreetScript : MonoBehaviour {
ok, eu sempre dou "<nome>Script" para meus scripts, vou mudar isso.

2017-05-30 21:37 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +public class SpawnStreetScript : MonoBehaviour {
Cara bem superficialmente:
O Factory ele é utilizado mais quando vc tem uma classe que cria instancia de objetos com a chamada de um método, exemplo:

var hamburgerXTudo = HamburgerFactory.createXTudo()

Já o Builder voce montar um objeto como se ele fosse um pedido do Macdonald's:

var hamburgerXTudo = hamburgerBuilder().createMeat().createBread().createSalad().createEgg().createBacon()

2017-05-30 21:41 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +public class SpawnStreetScript : MonoBehaviour {
Só lembrando que o Factory e Builder são Design Patterns e cada um tem uma aplicação diferente  eheheheh.. mais não se preocupe com eles muito agora.. Mas se quiser saber mais vou te passar um link

2017-05-30 22:17 UTC, mendesbarreto requested changes

2017-05-30 22:17 UTC, mendesbarreto commented on Assets/Scripts/SpawnStreetScript.cs
> +	public GameObject street1;
Antes de mais nada **ainda** não estamos pensando em reaproveitamento de código para essa classe, pois não temos a necessidade de escrever-la para uma futura reutilização, pois nesse momento ela irá funcionar em um local bem especifico e receberá objetos que sabemos quais serão. Isso já nos leva a ter essa classe com um nível de especialização alta.

Nesse caso as variáveis não podem conter nomes genericos e sim os nomes dos tipos dos objetos que elas irão receber, por exemplo:

cityStreet, countryStreet e highwayStreet

Se caso esses gameObj forem utilizados como tipos para serem instanciados:

cityStreetType, countryStreetType e highwayStreetType

Mostrei seu codigo para um dos meus amigo aqui e deu a impressão que street1, 2, 3 seria ruas que ficariam paralelas (left, right, center) a mesma impressão que tive, por isso que nesses casos a especialização dos nomes são importantes

Caso vc quisesse ter uma classe generica futuramente eu te aconselharia a ter uma collection de ruas ao invez de cravar a quantidade delas na mão e faria um algoritimo que pegasse quanto o jogador tinha que percorrer para mudar o cenário

2017-05-31 18:53 UTC, mendesbarreto requested changes

2017-05-31 18:53 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private int cont = 0;
Dois fix dessa Variável, vocês quiz escrever contador? 
Acredito que seria` private int count` 
E outra coisa que o count deve se referir ao que ele está contando, por exemplo timeChangeCounter

2017-05-31 18:53 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject country;
Faltou colocar Street no final do nome da variável como vc fez no city countryStreet

2017-05-31 18:53 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject highway;
Faltou colocar Street no final do nome da variável como vc fez no city, ex: highwayStreet

2017-05-31 18:53 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +		if (MoveStreet.isDestroyed == true)
Cara o MoveStreet.isDestroyed está sendo utilizado para controlar sua própria instancia isso não é correto, ou seja o comportamento do objeto MoveStreet é alterado por uma variável estática. 

Uma variável que define o estado de objeto de instancia não pode ser estático, pois, se em algum caso eu for utilizar essa classe e mais de um lugar vou ter muitos problemas, pois o isDestroyed tem que pertencer ao objeto e não a tabela estática da classe.

Para isso vc poderia criar uma variavel dentro da sua classe e ela vai apontar para uma instancia do MoveStreet, vc vai ter que procurar o gameObject e depois pegar o componente referente a ele

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Change the visibility of 'isDestroyed' or make it 'const' or 'readonly'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject highwayStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private void Start(){
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Start'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove this initialization to 'isDestroyed', the compiler will do that for you.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private void Update () {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Update'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject countryStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +			isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make the enclosing instance method 'static' or remove this set on the 'static' field.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject highwayStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'highwayStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject countryStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'countryStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject cityStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private int timeChangeCounter = 0;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove this initialization to 'timeChangeCounter', the compiler will do that for you.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject cityStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'cityStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/MoveStreet.cs
> +	private void Update () {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Update'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented on Assets/Scripts/MoveStreet.cs
> +	private void Destroy()
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'Destroy' a static method.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-01 21:40 UTC, mendesbarreto commented
![Codacy](https://www.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 15
           
```


See the complete overview on [Codacy](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733&bid=4677097)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject highwayStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Change the visibility of 'isDestroyed' or make it 'const' or 'readonly'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private void Start(){
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Start'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +		if (isDestroyed == true)
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove this initialization to 'isDestroyed', the compiler will do that for you.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private void Update () {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Update'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject countryStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +			isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make the enclosing instance method 'static' or remove this set on the 'static' field.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject highwayStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'highwayStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject countryStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'countryStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject cityStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private int timeChangeCounter = 0;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove this initialization to 'timeChangeCounter', the compiler will do that for you.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject cityStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'cityStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/MoveStreet.cs
> +	private void Destroy()
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'Destroy' a static method.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented on Assets/Scripts/MoveStreet.cs
> +	private void Update () {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Update'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-02 15:09 UTC, mendesbarreto commented
![Codacy](https://www.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 16
           
```


See the complete overview on [Codacy](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733&bid=4677097)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/MoveStreet.cs
> +	private void Destroy()
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'Destroy' a static method.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/MoveStreet.cs
> +	private void Update () {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Update'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject highwayStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Change the visibility of 'isDestroyed' or make it 'const' or 'readonly'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +		if (isDestroyed == true)
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private void Start(){
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Start'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove this initialization to 'isDestroyed', the compiler will do that for you.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private void Update () {
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'Update'.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject countryStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public static bool isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +			isDestroyed = false;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make the enclosing instance method 'static' or remove this set on the 'static' field.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject highwayStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'highwayStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject countryStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'countryStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject cityStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make this field 'private' and encapsulate it in a 'public' property.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	private int timeChangeCounter = 0;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Remove this initialization to 'timeChangeCounter', the compiler will do that for you.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented on Assets/Scripts/StreetBuilder.cs
> +	public GameObject cityStreet;
![Codacy](https://www.codacy.com/assets/images/favicon.png) Issue found: [Make 'cityStreet' private.](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733)

2017-06-05 15:30 UTC, mendesbarreto commented
![Codacy](https://www.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 16
           
```


See the complete overview on [Codacy](https://www.codacy.com/app/mendes-barreto/BSToysGame/pullRequest?prid=684733&bid=4677097)

2017-06-07 19:18 UTC, merged